# Site settings
title: Ionel Gog
email: ionel@eecs.berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:
url:
twitter_username: ICGog
github_username:  ICGog

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"
